sudo: false
language: rust
rust:
 - beta
  - nightly
os:
  - linux
  - osx
env:
  global:
    - RUST_BACKTRACE=1
script:
  - cargo build
  - cargo test
  - cargo install --path .
  - cargo build-deps
